"""공통 에러 표준 — 명세서 v0.4 §9 / 3주차 보완 'error_code 카탈로그'.

응답 Body 표준: {"detail": "<사용자 안내>", "error_code": "<프론트 분기용>"}

사용법:
    raise AppError(409, "이미 참여한 파티입니다.", ErrorCode.PARTY_ALREADY_JOINED)
"""

from fastapi import HTTPException


class ErrorCode:
    # AUTH
    AUTH_REQUIRED = "AUTH_REQUIRED"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
    AUTH_INACTIVE_USER = "AUTH_INACTIVE_USER"
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_EMAIL_ALREADY_EXISTS = "AUTH_EMAIL_ALREADY_EXISTS"
    # PARTY
    PARTY_NOT_FOUND = "PARTY_NOT_FOUND"
    PARTY_ALREADY_JOINED = "PARTY_ALREADY_JOINED"
    PARTY_TIME_OVERLAP = "PARTY_TIME_OVERLAP"
    PARTY_FULL = "PARTY_FULL"
    PARTY_NOT_RECRUITING = "PARTY_NOT_RECRUITING"
    PARTY_GENDER_RULE_MISMATCH = "PARTY_GENDER_RULE_MISMATCH"
    PARTY_CREATOR_CANNOT_LEAVE = "PARTY_CREATOR_CANNOT_LEAVE"
    PARTY_NOT_JOINED = "PARTY_NOT_JOINED"
    PARTY_NOT_CANCELABLE = "PARTY_NOT_CANCELABLE"
    PARTY_MEMBER_REQUIRED = "PARTY_MEMBER_REQUIRED"
    # FARE
    FARE_CONFIG_MISSING = "FARE_CONFIG_MISSING"
    FARE_UPSTREAM_FAILED = "FARE_UPSTREAM_FAILED"
    FARE_ROUTE_NOT_FOUND = "FARE_ROUTE_NOT_FOUND"
    FARE_INFO_MISSING = "FARE_INFO_MISSING"
    # ADMIN
    ADMIN_REQUIRED = "ADMIN_REQUIRED"
    MASTER_ADMIN_REQUIRED = "MASTER_ADMIN_REQUIRED"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    INVALID_ROLE = "INVALID_ROLE"
    MASTER_ADMIN_PROTECTED = "MASTER_ADMIN_PROTECTED"
    LAST_ADMIN_CANNOT_BE_DEMOTED = "LAST_ADMIN_CANNOT_BE_DEMOTED"
    LAST_ADMIN_CANNOT_BE_DEACTIVATED = "LAST_ADMIN_CANNOT_BE_DEACTIVATED"
    ADMIN_INVALID_PARTY_STATUS = "ADMIN_INVALID_PARTY_STATUS"
    # COMMON
    VALIDATION_ERROR = "VALIDATION_ERROR"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    SERVER_ERROR = "SERVER_ERROR"
    FORBIDDEN = "FORBIDDEN"


# 명세서 §9 상태코드별 기본 error_code — AppError가 아닌 일반 HTTPException 보정용.
STATUS_DEFAULT_CODE: dict[int, str] = {
    400: ErrorCode.VALIDATION_ERROR,
    401: ErrorCode.AUTH_REQUIRED,
    403: ErrorCode.FORBIDDEN,
    404: ErrorCode.RESOURCE_NOT_FOUND,
    409: ErrorCode.VALIDATION_ERROR,
    422: ErrorCode.VALIDATION_ERROR,
    500: ErrorCode.SERVER_ERROR,
    502: ErrorCode.FARE_UPSTREAM_FAILED,
}


class AppError(HTTPException):
    """error_code를 함께 싣는 HTTPException. 전역 핸들러가 {detail, error_code}로 직렬화한다."""

    def __init__(self, status_code: int, detail: str, error_code: str):
        super().__init__(status_code=status_code, detail=detail)
        self.error_code = error_code
